### ISSUE TITLE
v2.0.30 Zoneinfo TypeError: function missing required argument 'key' (pos 1)

### ISSUE THREAD

**Issue by Yoda-BZH** [O365/python-o365#1005]
Hello,

v2.0.30 contains a bug with zoneinfo.Zoneinfo calls.

It's parameter is called `key`. Currently the parameter sent is `name`:
* https://github.com/O365/python-o365/commit/dcd1ac26e8906df0dd18819842388afa495485e6#diff-a45a38d41c8a78f46d8a2750d148c83f76f78465515d0dbc2b287e962fbf68b5R437

```
user@server:/usr/local/share/myscript# ./main.py 
Traceback (most recent call last):
  File "/usr/local/share/myscript/./main.py", line 307, in <module>
    main()
  File "/usr/local/share/myscript/./main.py", line 290, in main
    get_astreintes_events()
  File "/usr/local/share/myscript/./main.py", line 210, in get_astreintes_events
    for event in events:
  File "/usr/local/lib/python3.10/dist-packages/O365/calendar.py", line 1784, in <genexpr>
    events = (self.event_constructor(parent=self,
  File "/usr/local/lib/python3.10/dist-packages/O365/calendar.py", line 867, in __init__
    self.__start = self._parse_date_time_time_zone(start_obj, self.__is_all_day)
  File "/usr/local/lib/python3.10/dist-packages/O365/utils/utils.py", line 436, in _parse_date_time_time_zone
    timezone = zoneinfo.ZoneInfo(
TypeError: function missing required argument 'key' (pos 1)
```

I suppose le `name=` can be dropped.

OS: ubuntu 22.04
python version: 3.10.6-1~22.04
O365 version: 2.0.30

**Comment by janscas** [comment]
Can you test that this is the only error? I don't want to release each time. thanks

**Comment by Yoda-BZH** [comment]
I looked through dcd1ac26e8906df0dd18819842388afa495485e6 and didn't see any other call to `zoneinfo.ZoneInfo()`


Thank you !
