### ISSUE TITLE
Update_fields does not work on a field initially set to None

### ISSUE THREAD

**Issue by bip91** [O365/python-o365#1088]
Hi, 

in a Sharepoint list, if we have a field that is not initially set, it is not possible to update it to a new value. 

Explanation : 
i =  l.get_item_by_id(x)
i.fields                                                     # > does not contain any "Status" field as "Status" is not set for this item
i._parent.column_name_cw.value()   # > but this contain "Status" value

in that case, update_field raise an error :
>>> i.update_fields({'Status': 'Inactif'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruno/src/o365/lib/python3.12/site-packages/O365/sharepoint.py", line 154, in update_fields
    raise ValueError('"{}" is not a valid internal field name'.format(field))

This is due to the fact that self.fields exists, but not contains the field,
and second condition is never tested. 

    def _valid_field(self, field):
        # Verify the used field names are valid internal field names
        **valid_field_names = self.fields if self.fields \
            else self._parent.column_name_cw.values() \
            if self._parent \**
            else None
        if valid_field_names:
            return field in valid_field_names

My proposition would be to switch the 2 conditions like this : 
    def _valid_field(self, field):^M
        # Verify the used field names are valid internal field names^M
        **valid_field_names = self._parent.column_name_cw.values() if self._parent \
                            else self.fields if self.fields \
                            else None
        
        # If no parent is given, and no internal fields are defined assume correct, API will check^M
        if valid_field_names is None:
            return True**
        
        return field in valid_field_names^M

**Comment by alejcas** [comment]
Can you make a PR with this changes?
Thanks
