### ISSUE TITLE
Can't Refresh Token - missing parameter in body request

### ISSUE THREAD

**Issue by Gustavo935** [O365/python-o365#167]
Traceback (most recent call last):
  File "TestEmail.py", line 32, in <module>
    con.refresh_token()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\O365\connection.py", line 487, in refresh_token
    client_secret=client_secret))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests_oauthlib\oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_toke
n'.

**Comment by ykorzikowski** [comment]
Same here: 

```
INFO:O365.connection:Oauth Token is expired, fetching a new token
Traceback (most recent call last):
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/connection.py", line 539, in _internal_request
    **kwargs)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 330, in request
    http_method=method, body=data, headers=headers)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 196, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/python-fritz-office-365-sync/core.py", line 121, in <module>
    Core().run()
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/python-fritz-office-365-sync/core.py", line 24, in run
    heating = self.query_for_heating_periods(credentials)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/python-fritz-office-365-sync/core.py", line 101, in query_for_heating_periods
    calendar = schedule.get_calendar(calendar_name=conf['CALENDAR_NAME'])
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/calendar.py", line 1864, in get_calendar
    response = self.con.get(url, params=params)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/connection.py", line 626, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/connection.py", line 615, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/connection.py", line 551, in _internal_request
    self.refresh_token()
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/O365/connection.py", line 487, in refresh_token
    client_secret=client_secret))
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/Yannik/work/git/python-fritz-office-365-sync/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.
Trace ID: ...
Correlation ID: ...
Timestamp: 2019-01-12 23:48:23Z
```

**Comment by ykorzikowski** [comment]
I noticed that there is no `refresh_token`inside the `o365_token.txt`file. When adding `offline_access` to the scopes array in your implementation, then it is there. 

Testing if this is the fix.

**Comment by janscas** [comment]
Can you paste the code you use to authenticate?

**Comment by ykorzikowski** [comment]
https://github.com/ykorzikowski/python-fritz-office-365-sync/blob/6810fa3d9cd1b1e780e443586f39b758f4a06882/python-fritz-office-365-sync/core.py#L12

**Comment by ykorzikowski** [comment]
Ok I can confirm that `offline_access` scope will fix this issue.

**Comment by janscas** [comment]
> https://github.com/ykorzikowski/python-fritz-office-365-sync/blob/6810fa3d9cd1b1e780e443586f39b758f4a06882/python-fritz-office-365-sync/core.py#L12

It should work as it is

**Comment by Gustavo935** [comment]
> Can you paste the code you use to authenticate?

Here is my code:

#!/usr/bin/python
# -*- coding: utf-8 -*-

# from O365 import *
from O365 import Account
from O365 import Connection
import sys
import time
import subprocess
import os

try:
	body = "<h1> TEST BODY EMAIL FROM SHARED MAILBOX</h1>"
	body = body.replace('"'," ")
	body = body.replace('[',"")
	body = body.replace('\\n',"")
	body = body.replace(']',"")
	body = body.replace("'","")
	TIME = time.strftime('%d-%b-%Y')
	pathFile = 'C:/Load.xlsx'

	#AUTHENTICATION FLOW  Oauth Authentication 
	credentials = ('Client_Id','App_password')
	scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']
	con = Connection(credentials, scopes=scopes)
	url = con.get_authorization_url()
	# print(url)
	# result_url = input('Paste the result url here...')
	# con.request_token(result_url)
  
	account = Account(credentials=credentials, scopes=scopes)
	con.refresh_token()
	mailbox = account.mailbox()
	m = mailbox.new_message()
	m.to.add(['user@mail.com','user@mail.com'])
	m.cc.add(['user@mail.com','users@mail.com'])
	m.bcc.add(['user@mail.com','usera@mail.com'])
	m.sender.address = 'user@mail.com'  # changing the from address
	m.body = body
	m.attachments.add(pathFile)
	m.subject ='TEST EMAIL WITH TOKEN AUTH O365 PYTHON'
	m.send()
	
	print ("email sent")
except ValueError:
    print (ValueError)

**Comment by ykorzikowski** [comment]
Try adding `'offline_access'` to scopes.

**Comment by Gustavo935** [comment]
The refresh_token() method is still crashing. but now with the `offline_access` scope, I can see the property `"refresh_token"`  in the `o365_token.txt`
![image](https://user-images.githubusercontent.com/40240640/51123529-ee9f2b80-17e1-11e9-9ee6-8a73026532d8.png)
That means I can use this token file for the `expires_at": 1547483213.30544` seconds time?

**Comment by janscas** [comment]
First of all, you only need to authenticate once if you pass the `offline_access` scope. The following api calls will use the stored token.

> That means I can use this token file for the `expires_at": 1547483213.30544` seconds time?

This is what this project Readme says about this [here](https://github.com/O365/python-o365#authentication-flow):

> The access token only lasts 60 minutes, but the app will automatically request new tokens through the refresh tokens, but note that a refresh token only lasts for 90 days. So you must use it before or you will need to request a new access token again (no new consent needed by the user, just a login).
> 
> If your application needs to work for more than 90 days without user interaction and without interacting with the API, then you must implement a periodic call to Connection.refresh_token before the 90 days have passed.

You don't have to call `con.refresh_token` normally. This is done for you by the library automatically.

**Comment by Gustavo935** [comment]
Thanks for the support. I confirm that the refresh is done automatically with the mentioned scope.

and my script is running in a production environment :)

**Comment by saulcruz** [comment]
Thanks for all the help on this library, I understand that we don't have to call con.refresh_token as it is done automatically, however what happens after 90 days of use? how do we workaround this issue, I just tried calling the connection.refresh_token() and got the same error:

`oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.`

Is there an example of how to call this method if our application needs to work for more than 90 days without user interaction and without interacting with the API?

**Comment by cythaletheon** [comment]
Hit same issue as saulcruz - it appears the method account.authenticate is adding 'https://graph.microsoft.com/' to each scope value.   Manually trimming the scope parameters and submitting that to O365 returned a successful token with refresh token present.

**Comment by Scylla2020** [comment]
```
I initially got the token using
credentials = (client,secret)
account = Account(credentials)
account.authenticate(scopes=['onedrive_all','offline_access'])
```

This gives a url which I visit to sign in and I get the token file as expected. I then use the file for subsequent runs using

```

token_backend = FileSystemTokenBackend(token_path=r'C:\Users\UserX\OneDrive',token_filename='o365_token.txt')
account = Account(credentials, token_backend=token_backend)
```

I used this quite frequently but it still expired after a some months even with continuous use. I guess its because the token file never gets updated by the `FileSystemTokenBackend` method. So is there another way to login I can use to ensure the token always gets refreshed?
