### ISSUE TITLE
mailbox query - is not ?

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#193]
good afternoon,

is it possible to do an is not from or does not contain in a mailbox query?

i.e.

```
    account = Account((credentials.username, credentials.password))
    mailbox = account.mailbox()
    query = mailbox.new_query().on_attribute('from').doesnotcontain('bob@bob.com')
    messages = mailbox.get_messages(limit=25, query=query)
```

Thanks

**Comment by janscas** [comment]
use `query.negate`

But take care that although this O365 api allows all filter combinations to occur, the Ms Graph and Office 365 Rest api does not allow a lot of them.

Check the microsoft docs.

**Comment by ajwillo** [comment]
Thanks, would you happen to have a short sample of this?

**Comment by janscas** [comment]
`q.on_attribute('subject').startswith('hello').negate()`

it's extremely easy

**Comment by ajwillo** [comment]
thank you

**Comment by ajwillo** [comment]
I know this is old, but this doesn't seem to work on the from field currently, 

```
query = mailbox.new_query().on_attribute('from').contains('application@').negate()
e_messages = mailbox.get_messages(limit=50, query=query)
```

I'm not sure this is because these are calendar invites, and the sender(from) is itself , I'm trying to hide all the calendar related emails

**Comment by janscas** [comment]
Can you print the query object and paste it back?

**Comment by ajwillo** [comment]
here's all the output here
```
>>> from O365 import Account, Connection
>>> account = Account((credentials.username, credentials.password))
>>> mailbox = account.mailbox()
>>> query = mailbox.new_query().on_attribute('from').contains('application@').negate()
>>> e_messages = mailbox.get_messages(limit=25)
>>> for m in e_messages:
...  print(m.sender.address)
...

application@domain.com
application@domain.com
application@domain.com
application@domain.com
application@domain.com
application@domain.com
application@domain.com
application@domain.com
application@domain.com
alex@domain.com
application@domain.com
bob@domain.com
pwnotifications@domain.com
>>> query
Filter: contains(from/emailAddress/address, 'application@')
Order: None
Select: None
Expand: None
Search: None
```

**Comment by janscas** [comment]
Then It’s a bug. It should say “not contains(...”

**Comment by janscas** [comment]
ohh i see it's not a bug.

Try calling:

```python
query = mailbox.new_query().on_attribute('from').negate().contains('application@')
```

**Comment by ajwillo** [comment]
im seeing a not supported error now

```
>>> query = mailbox.new_query().on_attribute('from').negate().contains('application@')
>>> e_messages = mailbox.get_messages(limit=50, query=query)
Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/messages?%24top=50&%24filter=not+contains%28from%2FemailAddress%2Faddress%2C+%27it.oncall%40%27%29 | Error Message: Filter not supported.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/O365/mailbox.py", line 204, in get_messages
    response = self.con.get(url, params=params)
  File "/usr/local/lib/python3.6/site-packages/O365/connection.py", line 654, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/O365/connection.py", line 643, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/O365/connection.py", line 605, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/messages?%24top=50&%24filter=not+contains%28from%2FemailAddress%2Faddress%2C+%27it.oncall%40%27%29 | Error Message: Filter not supported.
>>> query
Filter: not contains(from/emailAddress/address, 'application@')
Order: None
Select: None
Expand: None
Search: None
>>>
```

**Comment by janscas** [comment]
Then it’s not supported by microsoft. You can ask on stackoverflow on how to do what you want

**Comment by ajwillo** [comment]
ok, thank you for your help anyway
