### ISSUE TITLE
MSOffice365Protocol example / Support

### ISSUE THREAD

**Issue by nkgiovannivl** [O365/python-o365#208]
Hi,

After reading the introduction, i need to use MSOffice365Protocol  to send e-mails with attachments greater than 4MB, so i started but i'm not achieving this goal, below my code, thanks!

```
from O365 import Account
from O365 import MSOffice365Protocol
    
my_protocol = MSOffice365Protocol(api_version='v2.0')
credentials = ('client_id', 'client_secret')
emailAcc = Account(credentials=credentials,protocol=my_protocol) 


if not emailAcc.is_authenticated:
    emailAcc.authenticate(scopes=['basic','https://outlook.office.com/Mail.Send'])
    
m = emailAcc.new_message()

m.to.add('somemail@gmail.com')
m.subject = 'Testing auto email!'
m.body = 'Email Test'
m.attachments.add('Y:\\11032019_094726_ManualUpload.xlsx')
m.send()
```

Then i'm receiving this error:
```
py -3.7 Y:\RO_RFID_Srv\email_mod.py
Client Error: 400 Client Error: Bad Request for url: https://outlook.office.com/api/v2.0/me/sendMail | Error Message: Required property is missing.
Traceback (most recent call last):
  File "Y:\RO_RFID_Srv\email_mod.py", line 35, in <module>
    m.send()
  File "C:\Python\Python37\lib\site-packages\O365\message.py", line 596, in send
    response = self.con.post(url, data=data)
  File "C:\Python\Python37\lib\site-packages\O365\connection.py", line 672, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "C:\Python\Python37\lib\site-packages\O365\connection.py", line 650, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "C:\Python\Python37\lib\site-packages\O365\connection.py", line 615, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://outlook.office.com/api/v2.0/me/sendMail | Error Message: Required property is missing.
```
 Thanks for your support

**Comment by nkgiovannivl** [comment]
Hi, my problem was that the file on attachment does not exist.

**Comment by 275761919** [comment]
By the way, the directory of the file must be absolute.

**Comment by janscas** [comment]
That’s not true.

Btw use pathlib.
