### ISSUE TITLE
account.storage() - 'NoneType' is not iterable

### ISSUE THREAD

**Issue by linickx** [O365/python-o365#274]
Hello,

I'm trying to run [the OneDrive example](https://github.com/O365/python-o365/blob/master/examples/onedrive_example.py), but after the log-in the `account.storage()` function dies with `TypeError: argument of type 'NoneType' is not iterable.` I've checked & re-checked delegated permission (_screenshot below_).

Any idea's on how to troubleshoot?

![image](https://user-images.githubusercontent.com/649661/60986191-d0e8f400-a336-11e9-90ab-d128937dc3e8.png)

```
$ python onedrive_example.py
/usr/local/lib/python3.7/site-packages/O365/connection.py:402: DeprecationWarning: The default redirect uri was changed in version 1.1.4. to "https://login.microsoftonline.com/common/oauth2/nativeclient". You may have to change the registered app "redirect uri" or pass he
re the old "redirect_uri"
  DeprecationWarning)
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=REDACTAED&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=offline_access+https%3A%2F%2Fgraph.microsoft.com%2F
Files.ReadWrite.All+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read&state=REDACTED&access_type=offline
Paste the authenticated url here: https://login.microsoftonline.com/common/oauth2/nativeclient?code=REDACTAED
Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.
Traceback (most recent call last):
  File "onedrive_example.py", line 200, in <module>
    main()
  File "onedrive_example.py", line 164, in main
    account = O365Account()
  File "onedrive_example.py", line 22, in __init__
    self.storage = self.account.storage()
  File "/usr/local/lib/python3.7/site-packages/O365/account.py", line 147, in storage
    return Storage(parent=self, main_resource=resource)
  File "/usr/local/lib/python3.7/site-packages/O365/drive.py", line 1654, in __init__
    main_resource=main_resource)
  File "/usr/local/lib/python3.7/site-packages/O365/utils/utils.py", line 331, in __init__
    else protocol.default_resource))
  File "/usr/local/lib/python3.7/site-packages/O365/utils/utils.py", line 352, in _parse_resource
    elif '@' in resource and not resource.startswith(USERS_RESOURCE):
TypeError: argument of type 'NoneType' is not iterable
$
$ # I have  token...
$ ls o365_token.txt 
o365_token.txt
$ 
$  # Commented out self.authenticate(scopes) because it shouldn't be needed now...
$ python onedrive_example.py
Traceback (most recent call last):
  File "onedrive_example.py", line 200, in <module>
    main()
  File "onedrive_example.py", line 164, in main
    account = O365Account()
  File "onedrive_example.py", line 22, in __init__
    self.storage = self.account.storage()
  File "/usr/local/lib/python3.7/site-packages/O365/account.py", line 147, in storage
    return Storage(parent=self, main_resource=resource)
  File "/usr/local/lib/python3.7/site-packages/O365/drive.py", line 1654, in __init__
    main_resource=main_resource)
  File "/usr/local/lib/python3.7/site-packages/O365/utils/utils.py", line 331, in __init__
    else protocol.default_resource))
  File "/usr/local/lib/python3.7/site-packages/O365/utils/utils.py", line 352, in _parse_resource
    elif '@' in resource and not resource.startswith(USERS_RESOURCE):
TypeError: argument of type 'NoneType' is not iterable
$
```

**Comment by janscas** [comment]
Can you paste the code you are executing without the tracebacks. Please don't paste sensitive information.

**Comment by linickx** [comment]
Hi @janscas thanks for responding! 

The code was [the OneDrive example in this repo,](https://github.com/O365/python-o365/blob/master/examples/onedrive_example.py) however today it is working so I'm a little confused.

Running the script now exits cleanly & uploads work.
```
$ python onedrive_example.py 
Invalid function name
$
$ python onedrive_example.py -f upload_file -s hello.txt -d TEMP                                                                                                                               
Uploading file hello.txt
$ 
 ```
I can only assume our o365 admin has changed something so will close the issue 😕 

Many thanks!
