### ISSUE TITLE
calendar.get_events(query=q, include_recurring=True) always fails

### ISSUE THREAD

**Issue by toyg** [O365/python-o365#279]
I'm using the example in readme, and it just fails.
```python
>>> calendar = schedule.get_calendar(calendar_name='Birthdays')
>>> q = calendar.new_query('start').greater_equal(dt.datetime(2018, 5, 20))
>>> q.chain('and').on_attribute('end').less_equal(dt.datetime(2019, 9, 1))
>>> birthdays = calendar.get_events(query=q, include_recurring=True)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "[redacted]/o365/O365/calendar.py", line 1633, in get_events
    raise ValueError("When 'include_recurring' is True you must provide a 'start' and 'end' datetimes inside a Query instance.")
ValueError: When 'include_recurring' is True you must provide a 'start' and 'end' datetimes inside a Query instance.
```

The code seems to loop on `query._filters` checking if they are tuples, which they are not:
```python
            if query and not isinstance(query, str):
                # ...
                for query_data in query._filters:
                    if not isinstance(query_data, tuple):
                        continue
```

That check always fails because _filters appear to be lists rather than tuples:
```python
>>> for qd in q._filters: 
    print('-- list? ', isinstance(qd, list))
    print(qd)
-- list? True
['start/dateTime', "start/dateTime ge '2018-05-20T00:00:00+00:00'", ('', 'start/dateTime', 'ge', "'2018-05-20T00:00:00+00:00'")]
-- list? False
ChainOperator.AND
-- list? True
['end/dateTime', "end/dateTime le '2019-09-01T00:00:00+00:00'", ('', 'end/dateTime', 'le', "'2019-09-01T00:00:00+00:00'")]
```
This means all items in `_filters` are skipped, so start and end are never detected.

I honestly don't know enough about Query to decide whether `_filters` should be lists or tuples, but an approach that would work for both would probably be something like:
```python
from collections.abc import Iterable
isinstance(query_data, Iterable)
```
This returns True for lists, tuples, and strings, but not for ChainOperator instances, which I guess is what we want to do there.

Tested on Python 3.7.3 and 2.7.16.

**Comment by janscas** [comment]
Yep that’s a bug I introduced a few days before... sorry. I’m currently testing to launch version 2.

Thanks

**Comment by janscas** [comment]
Fixed!

Thanks a lot!
