### ISSUE TITLE
"Error Message: The requested user 'email@domain.com' is invalid." For email

### ISSUE THREAD

**Issue by axk7812** [O365/python-o365#416]
I am attempting to use this library to run a background process to connect to an email box and read the contents. I've registered the App in Azure and provided user.read.all and mail.read admin permissions. Here is the below code i'm using 

 ```
from O365 import Account, FileSystemTokenBackend

client_id = "x"
client_secret = "x"
tenant_id = "x"
address = "myemail@domain.com"

credentials = (client_id, client_secret)

# the default protocol will be Microsoft Graph

token_backend = FileSystemTokenBackend(token_path='token_folder', token_filename='my_token.txt')

account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant_id, token_backend=token_backend)

if account.authenticate():
    print('Authenticated!')

mailbox = account.mailbox(resource=address)

inbox = mailbox.inbox_folder()

for message in inbox.get_messages():
    print(message)
```

The app tells me it authenticates, however, I get the below error (I've replaced my actual email with the dummy email address) :

```

Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/users/myemail@domain.com/mailFolders/Inbox/messages?%24top=25 | Error Message: The requested user 'myemail@domain.com' is invalid.
Traceback (most recent call last):
  File "C:/Users/axk7812/Documents/Work/general-data/voip/run.py", line 94, in <module>
    email_5()
  File "C:/Users/axk7812/Documents/Work/general-data/voip/run.py", line 89, in email_5
    for message in inbox.get_messages():
  File "C:\Users\axk7812\AppData\Local\Continuum\anaconda3\envs\voip\lib\site-packages\O365\mailbox.py", line 212, in get_messages
    response = self.con.get(url, params=params)
  File "C:\Users\axk7812\AppData\Local\Continuum\anaconda3\envs\voip\lib\site-packages\O365\connection.py", line 778, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "C:\Users\axk7812\AppData\Local\Continuum\anaconda3\envs\voip\lib\site-packages\O365\connection.py", line 767, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "C:\Users\axk7812\AppData\Local\Continuum\anaconda3\envs\voip\lib\site-packages\O365\connection.py", line 729, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/users/myemail@domain.com/mailFolders/Inbox/messages?%24top=25 | Error Message: The requested user 'myemail@domain.com' is invalid.
```

For reference, I'm using Windows 10, python 3.8.1 and O365 2.0.7

Any hints as to what may be going on here?

**Comment by janscas** [comment]
The code is correct.

This error is returned when you have no access to the address provided.

**Comment by axk7812** [comment]
Ok I was actually able to get it running. I had to create new Microsoft 365 account. Just for testing I created a new MS 365 developer account. I'm not sure if this library will work for just a plain jane outlook account. I'm not super familiar with how all the Microsoft products are related but just adding this info here for reference in case encounters this issue.
