### ISSUE TITLE
Authentication error when scheduled as cron job

### ISSUE THREAD

**Issue by dwgreen1** [O365/python-o365#424]
I have a script in a Python venv that runs successfully when I run it directly, but when I run the script from a schedule cron job, I encounter an error that I'm unclear on how to troubleshoot. Below is the error I see (with the relevant piece for authenticating) when running via cron:

```
...
account = Account(
	credentials=credentials,
	main_resource='address@domain.com',
	scopes=['basic', 'message_all_shared', 'message_all']
)

if not account.is_authenticated:
	if account.authenticate(scopes=['basic', 'message_all_shared', 'message_all']):
		print('Authenticated!')
...

Traceback (most recent call last):
  File "/home/user/path-to-script.py", line 373, in <module>
    main()
  File "/home/user/path-to-script.py", line 47, in main
    if account.authenticate(scopes=['basic', 'message_all_shared', 'message_all']):
  File "/home/usr/venv/lib64/python3.6/site-packages/O365/account.py", line 87, in authenticate
    raise RuntimeError('The scopes must be set either at the Account instantiation or on the account.authenticate method.')
RuntimeError: The scopes must be set either at the Account instantiation or on the account.authenticate method.
```

Any thoughts on what I can try?

**Comment by janscas** [comment]
Just set the scopes on the authenticate method OR on the Account instantiation but not both.
