### ISSUE TITLE
Error The provided request must include a 'scope' input parameter. when using helpers and account

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#427]
Hello,

im running o365-2.0.9 and am coming across an issue authenticating scopes, the output is below: -

```
>>> creds = get_credentials('365 api')
>>> account = Account((creds.username, creds.password), auth_flow_type='credentials', tenant_id='*************1')
>>> my_desired_scopes = ['message_all','calendar_all','basic']
>>> account.authenticate(scopes=my_desired_scopes)
Unable to fetch auth token. Error: (invalid_scope) AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope message_all calendar_all basic is not valid.
Trace ID: 6f127854-04f1-4cef-b8af-d1d7bca71c00
Correlation ID: a602ff13-87c3-4ad0-9e29-ae212d6c9388
Timestamp: 2020-04-21 15:07:30Z
False
>>>
```

auth without scope works but then I cannot query the mailbox

```
>>> account.authenticate()
True
>>>
>>> messages = mailbox.get_messages(query=query)
Client Error: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/mailbox@mydomain.com/messages?%24top=25&%24filter=contains%28from%2FemailAddress%2Faddress%2C+%27%40mydomain.com%27%29+and+subject+eq+%27who%27+and+isRead+eq+false | Error Message: The token contains no permissions, or permissions can not be understood.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/O365/mailbox.py", line 212, in get_messages
    response = self.con.get(url, params=params)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 783, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 772, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 734, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/mailbox l@mydomain.com/messages?%24top=25&%24filter=contains%28from%2FemailAddress%2Faddress%2C+%27%40mydomain.com%27%29+and+subject+eq+%27who%27+and+isRead+eq+false | Error Message: The token contains no permissions, or permissions can not be understood.
```

token data

```
{
 "token_type": "Bearer",
 "expires_in": 3599,
 "ext_expires_in": 3599,
 "access_token": "ey...",
 "expires_at": 1587485648.0909579
}
```
thanks for your help

**Comment by janscas** [comment]
When authenticating with the auth flow type 'credentials' you don't have to pass any scopes.

Read carefully: https://github.com/O365/python-o365#authentication-steps

**Comment by ajwillo** [comment]
I thought that but then when I try search the mailbox I get that unauthorised error when I query? Am I doing something wrong there? 

Thanks

**Comment by janscas** [comment]
You have to set a resource. Like the email address of whom you are getting email from

**Comment by ajwillo** [comment]
Hi,

sorry I should of posted my full code, I did do this, but still got the error

Thanks for your help

```
>>> account = Account((creds.username, creds.password), auth_flow_type='credentials', tenant_id='*****')
>>> mailbox = account.mailbox(resource='mailbox1@mydomain.com')
>>> query = mailbox.new_query().on_attribute('from').contains('@mydomain.com')
>>> query = query.chain('and').on_attribute('subject').equals('who')
>>> query = query.chain('and').on_attribute('is_read').equals(False)
>>> messages = mailbox.get_messages(query=query)
Client Error: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/mailbox1@mydomain.com/messages?%24top=25&%24filter=contains%28from%2FemailAddress%2Faddress%2C+%27%40mydomain.com%27%29+and+subject+eq+%27who%27+and+isRead+eq+false | Error Message: The token contains no permissions, or permissions can not be understood.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/O365/mailbox.py", line 212, in get_messages
    response = self.con.get(url, params=params)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 783, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 772, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 734, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/mailbox1@mydomain.com/messages?%24top=25&%24filter=contains%28from%2FemailAddress%2Faddress%2C+%27%40mydomain.com%27%29+and+subject+eq+%27who%27+and+isRead+eq+false | Error Message: The token contains no permissions, or permissions can not be understood.
```

**Comment by janscas** [comment]
Then it's because you don't have access to mailbox1@mydomain.com mailbox or maybe the application permissions on azure AD are not correctly set.

**Comment by ajwillo** [comment]
I think ive got the perms right? screenshot below, not sure what im missing at the moment?
https://imgur.com/NpDidm8

**Comment by janscas** [comment]
Please, read the README.
**I again encourage you to read carefully through the README, as it's all explained there.**

Use application permissions, not delegated

**Comment by ajwillo** [comment]
Thanks, it was the application permissions, I added them but needed one of our admins to approve, everything now works as expected
