### ISSUE TITLE
sending mail have JSONDecodeError

### ISSUE THREAD

**Issue by HyeyeonKoo** [O365/python-o365#532]
Hello!
I have an issue about sending mail with O365 library.

There are two python file to send mail using O365 lib.

===code1.py===
send_auth_mail(email, token)

===code2.py===
def send_auth_mail(recipient, num):
    account = O365.Account(credentials)
    m = account.new_message()
    m.to.add(recipient)
    m.subject = '...'
    m.body = """..."""
    m.send()

With that codes, if i run code2.py, then mail is sended. But, if i run code1.py, then error is occurred like below.

Traceback (most recent call last):
  File "/home/metanet/workspace/atk_chatbot/kakao/main.py", line 297, in message
    send_auth_mail(email, token)
  File "/home/metanet/workspace/atk_chatbot/kakao/lib/o365_client.py", line 638, in send_auth_mail
    m.send()
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/message.py", line 694, in send
    response = self.con.post(url, data=data)
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/connection.py", line 811, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/connection.py", line 787, in oauth_request
    self.session = self.get_session(load_token=True)
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/connection.py", line 555, in get_session
    token = self.token_backend.get_token()
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/utils/token.py", line 94, in get_token
    self.token = self.load_token()  # store the token in the 'token' property
  File "/home/metanet/.pyenv/versions/3.7.0/envs/atk/lib/python3.7/site-packages/O365/utils/token.py", line 187, in load_token
    token = self.token_constructor(self.serializer.load(token_file))
  File "/home/metanet/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/metanet/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/metanet/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/metanet/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I couldn't follow this error's meaning. Could you help me? What is possibly wrong?

**Comment by janscas** [comment]
This is not related to the library.
Try to ask in another place why the subject or the body is not json serializable.

**Comment by HyeyeonKoo** [comment]
OK, Thank you
