### ISSUE TITLE
"403 Client Error" when I search file on onedrive

### ISSUE THREAD

**Issue by register110** [O365/python-o365#535]
Here is my API permissions:
![app_permission](https://user-images.githubusercontent.com/60174486/97154990-9f0bd300-17af-11eb-9865-03f46b62808e.PNG)

the code list below:
```
from O365 import Account

client_id = 'my_client_id '
tenant_id = 'my_tenant_id '
client_secret ='my_client_secret'


credentials = (client_id, client_secret)

# the default protocol will be Microsoft Graph

account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant_id)
if account.authenticate():
   print('Authenticated!')

   storage = account.storage()  # here we get the storage instance that handles all the storage options.

   # get the default drive
   my_drive = storage.get_default_drive()  # or get_drive('drive-id')
   root_folder = my_drive.get_root_folder()
   file = root_folder.search('p.xlsx', limit=1)
```
and the output is:
```Authenticated!
Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0//drive/items/01VYOENB56Y2GOVW7725BZO354PWSELRRZ/search(q='p.xlsx')?%24top=1 | Error Message: Access denied
Traceback (most recent call last):
  File "F:/rakuten_jp/office365.py", line 25, in <module>
    file = root_folder.search('p.xlsx', limit=1)
  File "D:\lib\site-packages\O365\drive.py", line 1194, in search
    response = self.con.get(url, params=params)
  File "D:\lib\site-packages\O365\connection.py", line 805, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "D:\lib\site-packages\O365\connection.py", line 794, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "D:\lib\site-packages\O365\connection.py", line 756, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0//drive/items/01VYOENB56Y2GOVW7725BZO354PWSELRRZ/search(q='p.xlsx')?%24top=1 | Error Message: Access denied

Process finished with exit code 1
```
It seem that I am not allow to access this api, why? Anything I miss on my code or azure?

**Comment by janscas** [comment]
When using the auth flow 'credentials' you have to tell the api  from which account you need to pull the data.
That's because when you authenticate using this method you are "The App" and not a user. 

That's what we call the 'resource'.

You can specify the resource on multiple places but for your use case change this:

`storage = account.storage(resource='my_account@domain.com')  # here we get the storage instance that handles all the storage options.`

**Comment by register110** [comment]
@janscas 

Thanks for reply. However it still not work, see the output below:
```
Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/users/my_account@domain.com/drive/items/01R4JTNOF6Y2GOVW7725BZO354PWSELRRZ/search(q='p.xlsx')?%24top=1 | Error Message: Access denied
Traceback (most recent call last):
  File "F:/rakuten_jp/office365.py", line 22, in <module>
    file = root_folder.search('p.xlsx', limit=1)
  File "D:\lib\site-packages\O365\drive.py", line 1194, in search
    response = self.con.get(url, params=params)
  File "D:\lib\site-packages\O365\connection.py", line 805, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "D:\lib\site-packages\O365\connection.py", line 794, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "D:\lib\site-packages\O365\connection.py", line 756, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/users/my_account@domain.com/drive/items/01R4JTNOF6Y2GOVW7725BZO354PWSELRRZ/search(q='p.xlsx')?%24top=1 | Error Message: Access denied

Process finished with exit code 1
```
The error is the same as before but the url is changed to `https://graph.microsoft.com/v1.0/users/my_account@domain.com/drive/items/01R4JTNOF6Y2GOVW7725BZO354PWSELRRZ/search(q='p.xlsx')?%24top=1`, when I query this url on [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) after I login, I get the right result, so it is sure that the url has the correct format. Also, I check the permissions of the example that Graph Explorer provides, nothing special.

Further, to investigate whether the current permission cause this problem, I try to new a folder and list the folder to check write and read permissions, see the code below:
```
from O365 import Account

client_id = 'my_client_id'
tenant_id = 'my_tenant_id'
client_secret ='my_client_secret'


credentials = (client_id, client_secret)

# the default protocol will be Microsoft Graph

account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant_id)
if account.authenticate():
   print('Authenticated!')

   storage = account.storage(resource='my_account@domain.com')  # here we get the storage instance that handles all the storage options.

   # get the default drive
   my_drive = storage.get_default_drive()  # or get_drive('drive-id')
   root_folder = my_drive.get_root_folder()
   
   root_folder.create_child_folder('create_for_test') # new a folder
   for floder in root_folder.get_child_folders(limit=5): # list first 5 folders
      print(floder)
```
and the code run successful:
```
Authenticated!
Folder: create_for_test
Folder: Documents
Folder: see

Process finished with exit code 0
```
It make me confuse, it seem that I could read/write on my onedrive, but not for the search operation, why?

**Comment by register110** [comment]
According to the [microsoft document](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http#permissions), it not only need **Files.Read.All, Files.ReadWrite.All** but also **Sites.Read.All, Sites.ReadWrite.All** .

**Comment by janscas** [comment]
great!
