### ISSUE TITLE
Required property is missing when trying to use inline image

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#565]
Hello,

im seeing the error below when trying to attach an inline image, when I send the mail without the images it works
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/user@domain.com/sendMail | Error Message: Required property is missing.`

I have tried to attach the image via url and by loading the image as bytes, both times I see that error, is there a way to show what property is missing?

here is adding the images as bytes, it adds two images when using the tuple?

```
>>> img = mail_template.mailimage_set.all()[0]
>>> # open the image from s3 bucket
>>> img_data = requests.get(signed_url(img.image.url))
>>> image = BytesIO(img_data.content)
>>> msg.attachments.add((image,img.image.url.split('/')[-1]))
>>> att = msg.attachments[0]
>>> att.is_inline = True
>>> att.content_id = 'image_1'
>>>
>>> list(msg.attachments)
[Attachment: None, Attachment: it_communication_maintenance.png]
>>> vars(list(msg.attachments)[0])
{'protocol': <O365.connection.MSGraphProtocol object at 0x7f48230eca58>, 'main_resource': 'users/user@domain.com', '_base_url': 'https://graph.microsoft.com/v1.0/users/user@domain.com', 'name': None, 'attachment_type': 'file', 'attachment_id': None, 'content_id': 'image_1', 'is_inline': True, 'attachment': None, 'content': None, 'on_disk': False, 'on_cloud': False, 'size': None}
>>> vars(list(msg.attachments)[1])
{'protocol': <O365.connection.MSGraphProtocol object at 0x7f48230eca58>, 'main_resource': 'users/user@domain.com', '_base_url': 'https://graph.microsoft.com/v1.0/users/user@domain.com', 'name': 'image_test.png', 'attachment_type': 'file', 'attachment_id': None, 'content_id': None, 'is_inline': False, 'attachment': PosixPath('image_test.png'), 'content': None, 'on_disk': False, 'on_cloud': False, 'size': None}
>>>
```

adding via url

```
>>> img = mail_template.mailimage_set.all()[0]
>>> # attach the image
>>> msg.attachments.add(signed_url(img.image.url))
>>> att = msg.attachments[0]
>>> att.is_inline = True
>>> att.content_id = 'image_1'
>>>
>>> list(msg.attachments)
[Attachment: image_test.png]
>>> vars(list(msg.attachments)[0])
{'protocol': <O365.connection.MSGraphProtocol object at 0x7f0f977e2a20>, 'main_resource': 'users/user@domain.com', '_base_url': 'https://graph.microsoft.com/v1.0/users/user@domain.com', 'name': 'image_test.png'), 'content': None, 'on_disk': False, 'on_cloud': False, 'size': None}
>>>
```

full traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/O365/message.py", line 695, in send
    response = self.con.post(url, data=data)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 816, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 794, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 756, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/user@domain.com/sendMail | Error Message: Required property is missing.
```

**Comment by ajwillo** [comment]
resolved by putting tuple into a list
