### ISSUE TITLE
Saving New Event raises TypeError, NoneType is not iterable

### ISSUE THREAD

**Issue by molson18** [O365/python-o365#569]
When executing the following snippet of code 

        if not alreadyExists:
            new_shift = calendar.new_event()
            new_shift.subject = user_info['subject']
            new_shift.start = shift.start_time
            new_shift.end = shift.end_time
            new_shift.save()
            print('added new shift: ', new_shift)

the new_shift.save() raises a TypeError exception with stacktrace:

        Traceback (most recent call last):
          File "C:/Users/.../PycharmProjects/ScheduleUpdater/Updater.py", line 133, in <module>
            insertShifts(scheduleParser(soup))
          File "C:/Users/.../PycharmProjects/ScheduleUpdater/Updater.py", line 97, in insertShifts
            new_shift.save()
          File "C:\Users\...\PycharmProjects\ScheduleUpdater\venv\lib\site-packages\O365\calendar.py", line 1432, in save
            data = self.to_api_data()
          File "C:\Users\...\PycharmProjects\ScheduleUpdater\venv\lib\site-packages\O365\calendar.py", line 967, in to_api_data
            if 'attachments' in restrict_keys:
        TypeError: argument of type 'NoneType' is not iterable

shift.start_time and shift.end_time are both just datetime objects and user_info['subject'] is a string

Edit: Changing back to version 2.0.10 fixes this problem

**Comment by janscas** [comment]
This was fixed on #554. But this change is not yet on pypi

**Comment by janscas** [comment]
New version 2.0.14 released on pypi
