### ISSUE TITLE
Basic attempt

### ISSUE THREAD

**Issue by JayBabs** [O365/python-o365#627]
Code : 
```

from O365 import Account
from O365.message import Message
from O365.mailbox import MailBox

credentials = ('XXXXXXX', 'XXXXXXX')

account = Account(credentials, auth_flow_type='credentials', tenant_id='XXXXXXXXXXXXXXXX')

if account.authenticate():
   print('Authenticated!')

mailbox = account.mailbox()

print(mailbox)

inbox = mailbox.inbox_folder()

print(inbox)
for message in inbox.get_messages():
    print(message)
```

`Authenticated!
MailBox from resource: 
Inbox from resource:
Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/mailFolders/Inbox/messages?%24top=25 | Error Message: Resource not found for the segment 'mailFolders'.
Traceback (most recent call last):
  File "\\stockagejb\jb\python\python_365\main.py", line 39, in <module>
    for message in inbox.get_messages():
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\O365\mailbox.py", line 212, in get_messages
    response = self.con.get(url, params=params)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\O365\connection.py", line 808, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\O365\connection.py", line 797, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\O365\connection.py", line 759, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None      
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/mailFolders/Inbox/messages?%24top=25 | Error Message: Resource not found for the segment 'mailFolders'.`

I'm able to authenticate and I'm sure that I got plenty of mail folders. Does anyone have a clue?

**Comment by DaniEzzeddine** [comment]
@JayBabs did you provide permissions on your azure app?

**Comment by janscas** [comment]
When using credentials you act as the app… you need to provide an account (aka email address) you have persimissions on to retrieve email.

**Comment by JayBabs** [comment]
How do you think I should correct it?
