### ISSUE TITLE
Can't send video file > 4 mb as attachment in email.

### ISSUE THREAD

**Issue by DiamondWrist** [O365/python-o365#654]
Hey! Anybody could help me?

```
def encode_video():
    with open("IMG_4273.MOV", "rb") as videoFile:
        text = videoFile.read()

        return text


credentials = (APP_ID, SECRET_KEY)
protocol = MSGraphProtocol(api_version='beta')

account = Account(credentials=credentials, scopes=scopes, protocol=protocol)
if account.authenticate():
    print('Authenticated!')
    mailbox = account.mailbox(resource='user:email@example.com')
    message = account.new_message(resource='user:email@example.com')
    # msg = account.new_message()
    message.subject = 'TEST123412'
    message.to.add('to_mail@example.com')

    from io import BytesIO
    data = BytesIO()
    data.write(encode_video())

    in_memory_attachment = (data, 'video.mp4')
    message.attachments.add([in_memory_attachment])  # HERE: in_memory_attachment is enclosed in a list
    att = message.attachments[0]  # get the attachment object

    body = """
        <html>
            <body>
                <strong>There should be an image here:</strong>
                <p>
                    TEST
                </p>
            </body>
        </html>
        """
    message.body = body
    message.save_draft()
```

And I have the following error:

```
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    message.save_draft()
  File "/Users/diamond/PycharmProjects/MSGraph/venv/lib/python3.8/site-packages/O365/message.py", line 977, in save_draft
    message = response.json()
  File "/Users/diamond/PycharmProjects/MSGraph/venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

When I use this method to save draft for attachment (photo, video) < 4 mb all is okay.

I will be appreciate for your help. Thanks!)

**Comment by DiamondWrist** [comment]
Here is solution:

```
credentials = (APP_ID, SECRET_KEY)
protocol = MSGraphProtocol(api_version='beta')
account = Account(credentials=credentials, scopes=SCOPES, protocol=protocol)

if account.authenticate():
    print('Authenticated!')
    mailbox = account.mailbox(resource=RESOURCE)
    message = account.new_message(resource=RESOURCE)
    # msg = account.new_message()
    message.subject = SUBJECT
    message.to.add(MAIL_TO)
    message.body = BODY
    message.save_message()

    message.attachments.add(f'{DIR_PATH}/{FILE}')
    resp = message.send()
```
