### ISSUE TITLE
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'zone'

### ISSUE THREAD

**Issue by Karthik-Nayak98** [O365/python-o365#679]
I am facing this error when I try to use calendar.

```
import datetime as dt
from O365 import Account, FileSystemTokenBackend
import os
import re

CLIENT_SECRET = 'xxxxxxx'
CLIENT_ID = 'xxxxxxxxxx'
TENANT_ID = 'xxxxxxxxxxxxxxx'
EMAIL_ID = 'xxxxxxxxxxxxxxx'

def calendar_event():
    credentials = (CLIENT_ID, CLIENT_SECRET)
    token_backend = FileSystemTokenBackend(token_path=os.getcwd(), token_filename='my_token.txt')
    account = Account(credentials, tenant_id=TENANT_ID, auth_flow_type='credentials', token_backend=token_backend)

    # Checking whether the client is authenticated.
    if not account.is_authenticated:
        try:
            account.authenticate()
            print('Authenticated!\n')
        except Exception as e:
            print("Exception: ", e)
            print("Authentication Failed!\n")
    else:
        print('Already Authenticated!\n')

    schedule = account.schedule(resource=EMAIL_ID)
    # print(schedule)

    calendar = schedule.get_default_calendar()
    print(calendar)

    new_event = calendar.new_event()  # creates a new unsaved event
    # print(new_event)
    new_event.subject = 'Recruit George Best!'
    new_event.location = 'England'

    # naive datetimes will automatically be converted to timezone aware datetime
    #  objects using the local timezone detected or the protocol provided timezone

    # new_event.start = datetime.now()
    new_event.start = dt.datetime(2021, 9, 7, 11, 45)

    # new_event.recurrence.set_daily(1, end=dt.datetime(2019, 9, 10))
    # new_event.remind_before_minutes = 45
    new_event.save()


if __name__ == '__main__':
    calendar_event()

```

### The error I am facing 
```
Traceback (most recent call last):
  File "C:\Users\karnayak\PycharmProjects\email_processing\calendar-processing.py", line 52, in <module>
    calendar_event()
  File "C:\Users\karnayak\PycharmProjects\email_processing\calendar-processing.py", line 35, in calendar_event
    new_event = calendar.new_event()  # creates a new unsaved event
  File "C:\Users\karnayak\PycharmProjects\email_processing\lib\site-packages\O365\calendar.py", line 1754, in new_event
Calendar: Calendar from Karthik Nayak (karthiknayak@gmail.com)
    return self.event_constructor(parent=self, subject=subject,
  File "C:\Users\karnayak\PycharmProjects\email_processing\lib\site-packages\O365\calendar.py", line 895, in __init__
    self.__recurrence = EventRecurrence(event=self,
  File "C:\Users\karnayak\PycharmProjects\email_processing\lib\site-packages\O365\calendar.py", line 137, in __init__
    get_windows_tz(self.protocol.timezone))
  File "C:\Users\karnayak\PycharmProjects\email_processing\lib\site-packages\O365\utils\windows_tz.py", line 639, in get_windows_tziana_tz.zone if isinstance(iana_tz, tzinfo) else iana_tz)
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'zone'

Process finished with exit code 1

```

**Comment by rena2damas** [comment]
Problem fixed in #671
Waiting for new release (#678)

In the meantime, you can pin version

```txt
tzlocal~=2.1
```

**Comment by Karthik-Nayak98** [comment]
When will the new version be released?

**Comment by rena2damas** [comment]
No idea , I am not an admin on this project.

**Comment by janscas** [comment]
I’ll try to release a new version today

**Comment by janscas** [comment]
> I’ll try to release a new version today

Done
