### ISSUE TITLE
Failed onedrive upload / program stuck

### ISSUE THREAD

**Issue by ghost** [O365/python-o365#712]
Sadly I don't have enough details and cannot reproduce this issue yet to collect them but I want to report what happened.

I had the program stuck during a file upload ([folder.upload_file()](https://github.com/O365/python-o365/blob/master/O365/drive.py#L1222)).

I gave it plenty of time and not only it wasn't exiting but it also forced the thread it was operating in to stay busy.

Maybe there's something in there that doesn't return a value and just keeps the whole thing waiting in such an edge case?

**Comment by janscas** [comment]
I could be something like this... never happen to me before tho...

If you somehow achieve a way to reproduce it let me know

**Comment by infosisio** [comment]
Hi @janscas, I was able to reproduce this.

What happens is consecutive server read timeouts, that are not affected by the timeout value you provide to requests.

Some of the errors:
```
TimeoutError: [Errno 110] Connection timed out

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Read timed out. (read timeout=None)

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Read timed out. (read timeout=None)

```

I had the timeout value set to 5 and as you can see it reports None.

Any way to address this?

**Comment by infosisio** [comment]
Pasting the full log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()     
  File "onedrive.py", line 77, in get_child_folder
    folder = self._get_child_folder(folder, _child_folder_name)
  File "onedrive.py", line 65, in _get_child_folder
    items = folder.get_items()
  File "/home/user/.local/lib/python3.9/site-packages/O365/drive.py", line 1057, in get_items
    response = self.con.get(url, params=params)
  File "/home/user/.local/lib/python3.9/site-packages/O365/connection.py", line 811, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/O365/connection.py", line 800, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/O365/connection.py", line 724, in _internal_request
    if self.refresh_token() is False:
  File "/home/user/.local/lib/python3.9/site-packages/O365/connection.py", line 633, in refresh_token
    self.session.refresh_token(
  File "/home/user/.local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 426, in refresh_token
    r = self.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Read timed out. (read timeout=None)
```

The error seems to be in refresh_token and kwargs are not provided there so timeout is not being supplied.

**Comment by alejcas** [comment]
This was fixed
