### ISSUE TITLE
Signing in users with the credential flow

### ISSUE THREAD

**Issue by cdw1984** [O365/python-o365#736]
Hi, 

First of thank you for you library. I'm trying to implement it in our Django backend and want to log users in using o365.  I am using the "With your own identity" flow and get a valid token back from the service. I am using the exact same code as in the documentation with the flask example. But when I get the authorization code with account.con.get_authorization_url(redirect_uri=redirect_uri, requested_scopes=scopes), I get the following error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/app/dashboard/views/authentication.py", line 55, in login_step1
>     url, state = account.con.get_authorization_url(redirect_uri=callback, requested_scopes=config365.scopes)
>   File "/usr/local/lib/python3.9/site-packages/O365/connection.py", line 462, in get_authorization_url
>     auth_url, state = oauth.authorization_url(
>   File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 165, in authorization_url
>     self._client.prepare_request_uri(
>   File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 139, in prepare_request_uri
>     raise NotImplementedError("Must be implemented by inheriting classes.")
> NotImplementedError: Must be implemented by inheriting classes.

Does anyone have an idea on what I do wrong?

**Comment by janscas** [comment]
maybe something changed in requests_oauthlib, don't know right now
