### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by sambathl** [O365/python-o365#74]
Traceback (most recent call last):
  File "calendar.py", line 1, in <module>
    from O365 import *
  File "/usr/local/lib/python2.7/dist-packages/O365/__init__.py", line 21, in <module>
    from .contact import Contact
  File "/usr/local/lib/python2.7/dist-packages/O365/contact.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py", line 35, in <module>
    from .request import RequestMethods
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/request.py", line 3, in <module>
    from .filepost import encode_multipart_formdata
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/filepost.py", line 9, in <module>
    from .fields import RequestField
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/fields.py", line 2, in <module>
    import email.utils
  File "/usr/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/calendar.py", line 3, in <module>
    schedule = Schedule(

**Comment by Narcolapser** [comment]
Can you give me a sample of your code?

**Comment by Narcolapser** [comment]
@sambathl Please elaborate on your problem a little bit and include a sample of your code and the end of your stack trace (where it details the problem). That should allow me to help you.

**Comment by roycem90** [comment]
Given this is way oldd and the api is completely changed, closing this..
