### ISSUE TITLE
Access Denied Error Response and Error Location

### ISSUE THREAD

**Issue by kambuchadrinker** [O365/python-o365#990]
**Description:**
When attempting to retrieve the calendar of a specific user, an "Access is denied" error with the code "ErrorAccessDenied" is encountered. This error occurs when the credentials used for the API request belong to a user who does not have an active subscription or the necessary permissions to access the calendar data of the target user.

**The response example:**
`{'error': {'code': 'ErrorAccessDenied', 'message': 'Access is denied. Check credentials and try again.'}}`

The error occurred in the connection.py file at line 796. 
`error.get("error", {}).get("innerError", "").get("code", "")`

The specific error message is:
**AttributeError: 'str' object has no attribute 'get'**

**Comment by janscas** [comment]
This is fixed in master but not yet released.

**Comment by EndermanAPM** [comment]
I'm also getting the same error when a 400 is risen on sendMail:
```
Traceback (most recent call last):
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/O365/connection.py", line 754, in _internal_request
    response.raise_for_status()  # raise 4XX and 5XX error codes.
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/beta/me/sendMail

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ftpUpload/ftpUpload.py", line 3369, in 
    email_success = createEmail(target_subproject_name)
  File "ftpUpload/ftpUpload.py", line 2359, in createEmail
    email_success = send_email_w_attachment(to_list, cc_list, subject, body, filenames)
  File "ftpUpload/ftpUpload.py", line 2031, in send_email_w_attachment
    m.send()
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/O365/message.py", line 720, in send
    response = self.con.post(url, data=data)
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/O365/connection.py", line 876, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/devel/matt/ftpupload_env/lib/python3.8/site-packages/O365/connection.py", line 796, in _internal_request
    error.get("error", {}).get("innerError", "").get("code", "")
AttributeError: 'str' object has no attribute 'get'
```

This obfuscates the reason the request failed and makes it harder to debug. Any idea on when this will be released?

**Comment by janscas** [comment]
This was already released.

Install latest version
